<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>fileTypes</key>
    <array>
      <string>oat</string>
    </array>
    <key>scopeName</key>
    <string>source.oat</string>
    <key>patterns</key>
    <array>
      <dict>
        <key>match</key>
        <string>\b(int|bool|string|void)\b</string>
        <key>name</key>
        <string>storage.type.oat</string>
      </dict>
      <dict>
        <key>name</key>
        <string>keyword.control.oat</string>
        <key>match</key>
        <string>\b(if|else|for|while|return|var|global|new)\b</string>
      </dict>
      <dict>
        <key>match</key>
        <string>\b(global|var)\b</string>
        <key>name</key>
        <string>storage.modifier.oat</string>
      </dict>
      <dict>
        <key>match</key>
        <string>;|,</string>
        <key>name</key>
        <string>punctuation.separator.oat</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#exp</string>
      </dict>
      <dict>
        <key>name</key>
        <string>keyword.operator.oat</string>
        <key>match</key>
        <string>\b(\+|-|\*|==|!=|&lt;|&lt;=|&gt;|&gt;=|&amp;|\||\[&amp;\]|\[\|\]|&lt;&lt;|&gt;&gt;|&gt;&gt;&gt;|!)\b</string>
      </dict>
      <dict>
        <key>name</key>
        <string>keyword.operator.assignment.oat</string>
        <key>match</key>
        <string>=</string>
      </dict>
    </array>
    <key>repository</key>
    <dict>
      <key>exp</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>\b(\d+)\b</string>
            <key>name</key>
            <string>constant.numeric.oat</string>
          </dict>
          <dict>
            <key>name</key>
            <string>constant.language.oat</string>
            <key>match</key>
            <string>\b(true|false|null)\b</string>
          </dict>
          <dict>
            <key>begin</key>
            <string>"</string>
            <key>end</key>
            <string>"</string>
            <key>name</key>
            <string>string.quoted.double</string>
          </dict>
          <dict>
            <key>begin</key>
            <string>([a-zA-Z][\w]*)\s*\(</string>
            <key>end</key>
            <string>\)</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>entity.name.function.oat</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>$self</string>
              </dict>
            </array>
            <key>name</key>
            <string>meta.function.call.oat</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b([a-zA-Z]\w*)\b</string>
            <key>name</key>
            <string>variable.other.oat</string>
          </dict>
        </array>
      </dict>
    </dict>
  </dict>
</plist>